on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-psr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx --from python-semantic-release psr -v -v -v version
